// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWGW0np3gu7G53fqE7atw0Zv28Sf9rvGI',
    appId: '1:458795377767:web:82efebb0cb6cf1deb5a0c2',
    messagingSenderId: '458795377767',
    projectId: 'rockpaperscissors-prit',
    authDomain: 'rockpaperscissors-prit.firebaseapp.com',
    storageBucket: 'rockpaperscissors-prit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZH0G48wppbDiIjkP4tsVZbnssZ0bPrLg',
    appId: '1:458795377767:android:c30a8475494b4c99b5a0c2',
    messagingSenderId: '458795377767',
    projectId: 'rockpaperscissors-prit',
    storageBucket: 'rockpaperscissors-prit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuT_eNs_GTev-GiWXPyYk1S8baTcqXHJQ',
    appId: '1:458795377767:ios:18b10a0f025a6ab7b5a0c2',
    messagingSenderId: '458795377767',
    projectId: 'rockpaperscissors-prit',
    storageBucket: 'rockpaperscissors-prit.firebasestorage.app',
    iosClientId: '458795377767-476cj0tfub550uv2kr1vvvqr82pd28lq.apps.googleusercontent.com',
    iosBundleId: 'com.example.rockPaperScissors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuT_eNs_GTev-GiWXPyYk1S8baTcqXHJQ',
    appId: '1:458795377767:ios:18b10a0f025a6ab7b5a0c2',
    messagingSenderId: '458795377767',
    projectId: 'rockpaperscissors-prit',
    storageBucket: 'rockpaperscissors-prit.firebasestorage.app',
    iosClientId: '458795377767-476cj0tfub550uv2kr1vvvqr82pd28lq.apps.googleusercontent.com',
    iosBundleId: 'com.example.rockPaperScissors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWGW0np3gu7G53fqE7atw0Zv28Sf9rvGI',
    appId: '1:458795377767:web:15d815201c5a4f9ab5a0c2',
    messagingSenderId: '458795377767',
    projectId: 'rockpaperscissors-prit',
    authDomain: 'rockpaperscissors-prit.firebaseapp.com',
    storageBucket: 'rockpaperscissors-prit.firebasestorage.app',
  );
}
